info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
server:
  port: ${PORT:9801}

queue:
#  interval-cron: '0 0 1-2 * * *'
#  interval-cron: '*/10 * * * * *'
  interval-cron: '0 */1 * * * *'
  remove-cron: '0 0 1 * * *'
  weather-7day-cron: '0 0 2 * * *'
  weather-today-cron: '0 0 8 * * *'
#  weather-today-cron: '0 */5 * * * *'
  weather-3-hours-cron: '0 0 */1 * * *'
#  weather-3-hours-cron: '0 */5 * * * *'
  enable: true
